[package]
name = "MinimalGo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "7.1.1" }
regex = { version = "1.6.0" }
llvm-ir = { version = "0.8.1", features = ["llvm-10"] }

[features]
default = []
riscv32 = []
riscv64 = []
